Feature: PublicLiabilityDetails page test

  Background: Step to Launch the URL in Browser
    Given PublicLiability Launch Browser and URL "https://uat.toolboxbyadmiral.com/public-liability"

  @Public_Liability_Excel
  Scenario: PublicLiability Sanity
    When PublicLiability Click on Accept All button in cookies popup
    And PublicLiability Process cj controls

  @PublicLiability
  Scenario: Title of your scenario outline
    When PublicLiability Click on Accept All button in cookies popup
    When PublicLiability Execute Userinfo Page
      | GetQuote | What’s your current occupation? | NextPage_Dy1|In what year was the business established? |  How many years of experience do you have? | NextPage_Dy2 | We just need some details about you.First Name | We just need some details about you.Last Name | We just need some details about you.DateBirth | What is your employment status? | NextPage_Dy3 | What’s your home address? | What’s your home FindAddress? | What’s your home SelectAddress? |Select Manual Address|Select Manual AddressLine1|Select Manual houseNameOrNumber|Select Manual addressLine3|Select Manual postcode| NextPage_Dy4 |  What’s your business email address? | What’s your business confirm email address? | What’s your business Mobile Number? | What’s your business alternative Mobile Number? | I agree to the T&Cs and Privacy Policy | marketing from Toolbox | NextPage_Dy5 |
      | TRUE     | Builder                         | TRUE        |2020                                       |  2 - 3 years                               | TRUE         | Jason                                          | Jason                                         | 04/02/1991                                    | I’m a sole trader               | TRUE         | CF104BZ                   | TRUE                          | TRUE                            |Skip                 |Skip                      |Skip                           |Skip                      |Skip                     | TRUE                                                              | joe.tester.smb@gmail.com            | joe.tester.smb@gmail.com                    | 7950438000                          | Skip                                            | TRUE                                   | Skip                   | TRUE         |
    And PublicLiability Fill Insurance Info and Claim Info Details
      | Bankruptcy | Past Insurance | Criminal records | Health & safety records | NextPage_Dy6 | Have you had any claims? | NextPage_Dy7 | Do you have a trading or company name? |Do you have a limited company name?| NextPage_Dy8 | NextPage_Dy9 | Do you have any parent or subsidiary companies? |Is your parent or subsidiary company covered under this policy?|What is the name of your parent or subsidiary company?| NextPage_Dy10 | What is your business yearly turnover? | NextPage_Dy11 | Do you need contract? works cover? |Contract value|What limit of indemnity do you require?| NextPage_Dy12 | What level of Public Liability cover do you require? cover do you require? | Is all your work within the UK? | NextPage_Dy13 | Do you have a separate dedicated business premises? dedicated business premises? | NextPage_Dy14 | Do you require hired in plant cover? |What level of cover do you require?|What is the your estimated annual costs for hiring in plant?| NextPage_Dy15 | Do you require own plant cover? |cover do you require?|What is the current total value of own plant equipment that you require cover for?| NextPage_Dy16 | Does your work involve any discharge of fumes, effluent or anything of a noxious nature? | Does your work involve the use of substances which could be harmful to health? | NextPage_Dy17 | Do you use any form of heat equipment? |Please select the tools you are using| NextPage_Dy18 | What is the maximum depth? at which work is undertaken? | What is the maximum height worked at? | NextPage_Dy19 | Is 3-phase work undertaken? | Is any gas fitting or installation work undertaken? | NextPage_Dy20 | Do you require Employers Liability insurance? | NextPage_Dy21 |
      | No         | No             | No               | No                      | TRUE         | No                       | TRUE         | No                                     |Skip                              | TRUE         | Skip         | No                                               |Skip                                                           |Skip                                         | TRUE          | 60000                                  | TRUE          | No                                          |Skip          |Skip                            | TRUE          | £2 million                                                                 | Yes                             | TRUE          | No                                                                               | TRUE          | No                                          |Skip                               |Skip                           | TRUE          | No                                                           |Skip                 |Skip                | TRUE          | No                                                                                       | No                                                                             | TRUE          | No                                                                                                   |Skip | TRUE          | 1 Meter                                                 | 15 Metres                             | TRUE          | Yes                         | No                                                  | TRUE          | No                                            | TRUE          |
    And PublicLiability Fill Business Info Address Details
      | How many partners / principles /proprietors or directors perform manual work?|How many partners / principles /proprietors or directors perform non-manual work?|How many employees perform manual work?|How many employees perform administrative tasks or non-manual work? | NextPage_Dy22 | How many labour-only subcontractors do you have at any given time? | How many bona fide subcontractors do you have at any given time? |   NextPage_Dy23|Are all your employees paid below the PAYE threshold?|Please provide your employer Reference Number (ERN)|NextPage_Dy24 | Do you require Professional Indemnity insurance? | NextPage_Dy25 |Do you currently hold a Professional Indemnity policy, with a retroactive date?|What is your retroactive date?|NextPage_Dy26|What level of Professional Indemnity cover do you require?|NextPage_Dy27|Do you undertake any structural, computer software or computer hardware design work?|NextPage_Dy28|Do you undertake any property management?|Do you give any taxation advice?|NextPage_Dy29|Do one or more of the business partners?|NextPage_Dy30| How do you want to pay? | When do you want to start the cover? | Auto Renew | NextPage_Dy31 |
      | 1                                                                            |Skip                                                                             |Skip                                   |Skip                                                              | TRUE          | 0                                                                  | 0                                                                |                                                                                                TRUE|Skip|Skip              |Skip    | No                                               | TRUE          |Skip                                                                                 |Skip                          |Skip         |Skip                                                      |Skip         |Skip                                                                                |Skip         |Skip                                     |Skip                            |Skip         |Skip                                    |Skip         | Annually                | Skip                                 | Skip       | TRUE          |

    And PublicLiability Fill Payment Details Page Info
      | I confirm I have read the above information | Click Continue To Payment | AccountHolderNameInfo | AccountSortcodeNameInfo | AccountNumberNameInfo | ConfirmPage | PayCardNumber       | PayCardHolder | Card ExpiryDateMonth | PayCardExpireSplitYear | CardSecurityCode | CardHolderHouseNumber | CardHolderAddressLine1 | CardHolderPostcode | ProposerIsCardHolder | CardAutoReuseConsent | nextbtn |
      | TRUE                                        | TRUE                | Skip              | Skip                  | Skip              | Skip        | 4444 3333 2222 1111 | Joe Boe       | 05                   | 2025                   | 123              | Boe                   | Boe                    | SA11 2JL           | TRUE                 | TRUE                 | TRUE    |

#    When I check for the <value> in step
    Then PublicLiability Publish reports


  #@tag2
  #Scenario Outline: Title of your scenario outline
    #Given I want to write a step with <name>
    #When I check for the <value> in step
    #Then I verify the <status> in step
#
    #Examples: 
      #| name  | value | status  |
      #| name1 |     5 | success |
      #| name2 |     7 | Fail    |
